/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_frostwire_android_python_PythonBridge */

#ifndef _Included_com_frostwire_android_python_PythonBridge
#define _Included_com_frostwire_android_python_PythonBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_frostwire_android_python_PythonBridge
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_frostwire_android_python_PythonBridge_square
  (JNIEnv *, jclass, jint);

void python_vm_test();
  
#ifdef __cplusplus
}
#endif
#endif
